### ISSUE TITLE
ModuleNotFoundError: No module named 'base'

### ISSUE THREAD

**Issue by hp962183985** [LuYF-Lemon-love/pybind11-OpenKE#1]
请问遇到这个问题怎么办？而且install base好像也不管用

**Comment by yanfeng98** [comment]
请问您是运行在windows上吗

**Comment by hp962183985** [comment]
> 请问您是运行在windows上吗

您好，我是运行在mac上的

**Comment by hp962183985** [comment]
而且在bash make.sh的时候还会报 
No module named pybind11
In file included from ./base/Base.cpp:8:
./base/Setting.h:19:10: fatal error: 'pybind11/pybind11.h' file not found
#include <pybind11/pybind11.h>                                          // 导入 pybind11
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
这样的错误

**Comment by yanfeng98** [comment]
好像不需要 bash make.sh ，目前已经用 [Setuptools](https://setuptools.pypa.io/en/latest/) 给打包了。

$ git clone -b pybind11-OpenKE-PyTorch git@github.com:LuYF-Lemon-love/pybind11-OpenKE.git --depth 1
$ cd pybind11-OpenKE/
$ pip install .

您看看这个能否安装
